-- 自動生成: python3 scripts/generate_seed.py > supabase/seed.sql
-- 実在ブランドの成分表は転載していない。ブランド名・商品名・口コミはすべて架空のデモデータ。

truncate table reviews, user_items, product_colors, products, brands, ingredients_master restart identity cascade;

insert into ingredients_master (dim, inci, name_ja, functions, hazard_tags) values
  (1, 'HYDROGENATED POLYISOBUTENE', null, array[]::text[], array[]::text[]),
  (2, 'DIISOSTEARYL MALATE', null, array[]::text[], array[]::text[]),
  (3, 'POLYETHYLENE', null, array[]::text[], array[]::text[]),
  (4, 'MICROCRYSTALLINE WAX', null, array[]::text[], array[]::text[]),
  (5, 'CANDELILLA WAX', null, array[]::text[], array[]::text[]),
  (6, 'OCTYLDODECANOL', null, array[]::text[], array[]::text[]),
  (7, 'CERA ALBA', null, array[]::text[], array[]::text[]),
  (8, 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', null, array[]::text[], array[]::text[]),
  (9, 'TOCOPHEROL', 'トコフェロール', array['antioxidant']::text[], array[]::text[]),
  (10, 'JOJOBA ESTERS', null, array[]::text[], array[]::text[]),
  (11, 'RICINUS COMMUNIS SEED OIL', null, array[]::text[], array[]::text[]),
  (12, 'SILICA', null, array[]::text[], array[]::text[]),
  (13, 'TRIMETHYLSILOXYSILICATE', null, array[]::text[], array[]::text[]),
  (14, 'ISODODECANE', null, array[]::text[], array[]::text[]),
  (15, 'DIMETHICONE', 'ジメチコン', array['emollient', 'silicone']::text[], array[]::text[]),
  (16, 'SYNTHETIC FLUORPHLOGOPITE', null, array[]::text[], array[]::text[]),
  (17, 'MICA', 'マイカ', array[]::text[], array[]::text[]),
  (18, 'SIMMONDSIA CHINENSIS SEED OIL', null, array[]::text[], array[]::text[]),
  (19, 'SQUALANE', 'スクワラン', array[]::text[], array[]::text[]),
  (20, 'SHEA BUTTER ETHYL ESTERS', null, array[]::text[], array[]::text[]),
  (21, 'POLYGLYCERYL-2 TRIISOSTEARATE', null, array[]::text[], array[]::text[]),
  (22, 'CAPRYLIC/CAPRIC TRIGLYCERIDE', null, array[]::text[], array[]::text[]),
  (23, 'TITANIUM DIOXIDE', '酸化チタン', array['uv', 'pigment']::text[], array[]::text[]),
  (24, 'CI 15850', null, array[]::text[], array[]::text[]),
  (25, 'CI 45410', null, array[]::text[], array[]::text[]),
  (26, 'CI 77491', null, array[]::text[], array[]::text[]),
  (27, 'CI 77891', null, array[]::text[], array[]::text[]),
  (28, 'CI 19140', null, array[]::text[], array[]::text[]),
  (29, 'CI 42090', null, array[]::text[], array[]::text[]),
  (30, 'TOCOPHERYL ACETATE', null, array[]::text[], array[]::text[]),
  (31, 'HYALURONIC ACID', 'ヒアルロン酸', array[]::text[], array[]::text[]),
  (32, 'WATER', '水', array['base']::text[], array[]::text[]),
  (33, 'CYCLOPENTASILOXANE', null, array[]::text[], array[]::text[]),
  (34, 'ETHYLHEXYL METHOXYCINNAMATE', null, array[]::text[], array['sensitive-skin']::text[]),
  (35, 'GLYCERIN', 'グリセリン', array['humectant']::text[], array[]::text[]),
  (36, 'PEG-10 DIMETHICONE', null, array[]::text[], array[]::text[]),
  (37, 'TALC', 'タルク', array[]::text[], array[]::text[]),
  (38, 'BUTYLENE GLYCOL', null, array[]::text[], array[]::text[]),
  (39, 'SODIUM CHLORIDE', null, array[]::text[], array[]::text[]),
  (40, 'IRON OXIDES', '酸化鉄', array[]::text[], array[]::text[]),
  (41, 'PHENOXYETHANOL', 'フェノキシエタノール', array['preservative']::text[], array[]::text[]),
  (42, 'ALUMINUM HYDROXIDE', null, array[]::text[], array[]::text[]),
  (43, 'TRIETHOXYCAPRYLYLSILANE', null, array[]::text[], array[]::text[]),
  (44, 'ZINC OXIDE', '酸化亜鉛', array['uv', 'pigment']::text[], array[]::text[]),
  (45, 'DISTEARDIMONIUM HECTORITE', null, array[]::text[], array[]::text[]),
  (46, 'LAURYL PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE', null, array[]::text[], array[]::text[]),
  (47, 'METHICONE', null, array[]::text[], array[]::text[]),
  (48, 'GLYCERYL CAPRYLATE', null, array[]::text[], array[]::text[]),
  (49, 'CI 77492', null, array[]::text[], array[]::text[]),
  (50, 'CI 77499', null, array[]::text[], array[]::text[]),
  (51, 'ASCORBYL GLUCOSIDE', null, array[]::text[], array[]::text[]),
  (52, 'NIACINAMIDE', 'ナイアシンアミド', array['brightening']::text[], array[]::text[]),
  (53, 'PANTHENOL', 'パンテノール', array['conditioning']::text[], array[]::text[]),
  (54, 'CITRIC ACID', 'クエン酸', array[]::text[], array[]::text[]),
  (55, 'SODIUM LAURETH SULFATE', 'ラウレス硫酸Na', array['surfactant']::text[], array['harsh-surfactant']::text[]),
  (56, 'COCAMIDOPROPYL BETAINE', 'コカミドプロピルベタイン', array['surfactant']::text[], array[]::text[]),
  (57, 'COCAMIDE MEA', null, array[]::text[], array[]::text[]),
  (58, 'MENTHOL', 'メントール', array['sensory']::text[], array['sensitive-skin']::text[]),
  (59, 'PIROCTONE OLAMINE', 'ピロクトンオラミン', array['anti-dandruff']::text[], array[]::text[]),
  (60, 'ZINC PYRITHIONE', 'ピロクトンオラミン系(ジンクピリチオン)', array['anti-dandruff']::text[], array['restricted-eu']::text[]),
  (61, 'SALICYLIC ACID', 'サリチル酸', array['exfoliant']::text[], array[]::text[]),
  (62, 'HYDROLYZED KERATIN', null, array[]::text[], array[]::text[]),
  (63, 'ARGANIA SPINOSA KERNEL OIL', null, array[]::text[], array[]::text[]),
  (64, 'POLYQUATERNIUM-10', null, array[]::text[], array[]::text[]),
  (65, 'FRAGRANCE', '香料', array['fragrance']::text[], array['sensitive-skin']::text[]),
  (66, 'SODIUM BENZOATE', null, array[]::text[], array[]::text[]),
  (67, 'DISODIUM EDTA', null, array[]::text[], array[]::text[]),
  (68, 'LAURAMIDOPROPYL BETAINE', null, array[]::text[], array[]::text[]),
  (69, 'SODIUM COCOYL GLUTAMATE', null, array[]::text[], array[]::text[]),
  (70, 'GLYCOL DISTEARATE', null, array[]::text[], array[]::text[]),
  (71, 'MENTHYL LACTATE', null, array[]::text[], array[]::text[]),
  (72, 'CAMELLIA SINENSIS LEAF EXTRACT', null, array[]::text[], array[]::text[]),
  (73, 'BIOTIN', null, array[]::text[], array[]::text[]),
  (74, 'ISOPROPYL METHYLPHENOL', null, array[]::text[], array[]::text[]),
  (75, 'SODIUM HYALURONATE', null, array[]::text[], array[]::text[]),
  (76, 'CETEARYL ALCOHOL', null, array[]::text[], array[]::text[]),
  (77, 'BEHENTRIMONIUM CHLORIDE', null, array[]::text[], array[]::text[]),
  (78, 'AMODIMETHICONE', null, array[]::text[], array[]::text[]),
  (79, 'STEARYL ALCOHOL', null, array[]::text[], array[]::text[]),
  (80, 'ISOPROPYL MYRISTATE', null, array[]::text[], array[]::text[]),
  (81, 'ZINC STEARATE', null, array[]::text[], array[]::text[]),
  (82, 'CALCIUM ALUMINUM BOROSILICATE', null, array[]::text[], array[]::text[]),
  (83, 'MAGNESIUM MYRISTATE', null, array[]::text[], array[]::text[]),
  (84, 'BORON NITRIDE', null, array[]::text[], array[]::text[]),
  (85, 'TIN OXIDE', null, array[]::text[], array[]::text[]);

insert into brands (name) values
  ('LUMINA'),
  ('SERAFI'),
  ('PLUME'),
  ('KIRA COSME'),
  ('mode noir'),
  ('PRICO'),
  ('DAILY+'),
  ('Nuance'),
  ('GRIT'),
  ('HARDSCALP'),
  ('CLEAR BASE'),
  ('STOIC');

insert into products (brand_id, name, category, is_mens, price_yen, volume, volume_unit, jan, color_hex, ingredients) values
  ((select id from brands where name = 'LUMINA'), 'グロウリップスティック 03 テラコッタ', 'lip', false, 3800, 3.5, 'g', '4901234000007', '#B8604A', array['HYDROGENATED POLYISOBUTENE', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'JOJOBA ESTERS', 'SQUALANE', 'TOCOPHEROL', 'CI 45410', 'CI 15850', 'CI 42090', 'CI 19140']::text[]),
  ((select id from brands where name = 'PRICO'), 'メルティリップ 03 テラコッタ', 'lip', false, 980, 3.5, 'g', '4901234000014', '#BB6249', array['水添ポリイソブテン', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'JOJOBA ESTERS', 'ビタミンE', 'スクワラン', 'CI 45410', 'CI 77891', 'CI 42090', '酸化鉄（赤）']::text[]),
  ((select id from brands where name = 'SERAFI'), 'ヴェルベットティント 05 レッドブリック', 'lip', false, 3200, 3.5, 'g', '4901234000021', '#9E3B33', array['ISODODECANE', 'TRIMETHYLSILOXYSILICATE', 'DIMETHICONE', 'SILICA', 'POLYGLYCERYL-2 TRIISOSTEARATE', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'SYNTHETIC FLUORPHLOGOPITE', 'CERA ALBA', 'TOCOPHERYL ACETATE', 'CI 15850', 'CI 42090', 'MICA', 'CI 19140']::text[]),
  ((select id from brands where name = 'DAILY+'), 'デイリーティント 05 レッドブリック', 'lip', false, 1100, 3.5, 'g', '4901234000028', '#993B2D', array['ISODODECANE', 'TRIMETHYLSILOXYSILICATE', 'DIMETHICONE', 'SILICA', 'POLYGLYCERYL-2 TRIISOSTEARATE', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'CERA ALBA', 'SYNTHETIC FLUORPHLOGOPITE', 'TOCOPHERYL ACETATE', 'CI 77491', 'CI 19140', 'MICA', 'CI 15850', 'ツバキ種子油']::text[]),
  ((select id from brands where name = 'PLUME'), 'シアーリップバーム 01 ベアヌード', 'lip', false, 2400, 3.5, 'g', '4901234000035', '#C98A78', array['HYDROGENATED POLYISOBUTENE', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'JOJOBA ESTERS', 'SQUALANE', 'TOCOPHEROL', 'CI 77491', 'CI 77891', 'CI 15850', 'CI 42090']::text[]),
  ((select id from brands where name = 'Nuance'), 'ニュアンスリップ 04 モーヴピンク', 'lip', false, 1580, 3.5, 'g', '4901234000042', '#B96C81', array['HYDROGENATED POLYISOBUTENE', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'JOJOBA ESTERS', 'SQUALANE', 'TOCOPHEROL', 'CI 42090', 'MICA', 'CI 19140', 'TITANIUM DIOXIDE']::text[]),
  ((select id from brands where name = 'KIRA COSME'), 'シャインリップ 06 コーラルオレンジ', 'lip', false, 2900, 3.5, 'g', '4901234000049', '#D96A4B', array['ISODODECANE', 'TRIMETHYLSILOXYSILICATE', 'DIMETHICONE', 'SILICA', 'POLYGLYCERYL-2 TRIISOSTEARATE', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'SYNTHETIC FLUORPHLOGOPITE', 'CERA ALBA', 'TOCOPHERYL ACETATE', 'CI 19140', 'CI 77491', 'TITANIUM DIOXIDE', 'CI 42090']::text[]),
  ((select id from brands where name = 'mode noir'), 'マットリップ 07 ダークプラム', 'lip', false, 4200, 3.5, 'g', '4901234000056', '#7A3348', array['ISODODECANE', 'TRIMETHYLSILOXYSILICATE', 'DIMETHICONE', 'SILICA', 'POLYGLYCERYL-2 TRIISOSTEARATE', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'SYNTHETIC FLUORPHLOGOPITE', 'CERA ALBA', 'TOCOPHERYL ACETATE', 'CI 15850', 'CI 45410', 'CI 77491', 'TITANIUM DIOXIDE']::text[]),
  ((select id from brands where name = 'PRICO'), 'プチプラリップ 08 ミルクティー', 'lip', false, 750, 3.5, 'g', '4901234000063', '#C79A82', array['HYDROGENATED POLYISOBUTENE', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'JOJOBA ESTERS', 'SQUALANE', 'TOCOPHEROL', 'MICA', 'CI 77891', 'CI 77491', 'TITANIUM DIOXIDE']::text[]),
  ((select id from brands where name = 'DAILY+'), 'うるおいリップ 02 ローズブラウン', 'lip', false, 890, 3.5, 'g', '4901234000070', '#A85F5A', array['HYDROGENATED POLYISOBUTENE', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'JOJOBA ESTERS', 'SQUALANE', 'TOCOPHEROL', 'CI 15850', 'CI 19140', 'CI 77891', 'MICA']::text[]),
  ((select id from brands where name = 'Nuance'), 'モーヴティント 04 モーヴピンク', 'lip', false, 1780, 3.5, 'g', '4901234000077', '#BC687E', array['ISODODECANE', 'TRIMETHYLSILOXYSILICATE', 'DIMETHICONE', 'POLYGLYCERYL-2 TRIISOSTEARATE', 'SILICA', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'SYNTHETIC FLUORPHLOGOPITE', 'CERA ALBA', 'TOCOPHERYL ACETATE', 'TITANIUM DIOXIDE', 'CI 77891', 'CI 19140', 'MICA']::text[]),
  ((select id from brands where name = 'PLUME'), 'コーラルリップ 06 コーラルオレンジ', 'lip', false, 2600, 3.5, 'g', '4901234000084', '#D6684E', array['HYDROGENATED POLYISOBUTENE', 'DIISOSTEARYL MALATE', 'POLYETHYLENE', 'MICROCRYSTALLINE WAX', 'CANDELILLA WAX', 'OCTYLDODECANOL', 'PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE', 'SQUALANE', 'JOJOBA ESTERS', 'TOCOPHEROL', 'TITANIUM DIOXIDE', 'CI 15850', 'CI 77891', 'CI 42090']::text[]),
  ((select id from brands where name = 'LUMINA'), 'スキンフィットファンデーション 200 ナチュラルオークル', 'foundation', false, 6200, 30, 'mL', '4901234000091', '#DDB18C', array['WATER', 'CYCLOPENTASILOXANE', 'ETHYLHEXYL METHOXYCINNAMATE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'PEG-10 DIMETHICONE', 'BUTYLENE GLYCOL', 'TALC', 'TRIETHOXYCAPRYLYLSILANE', 'SODIUM CHLORIDE', 'DISTEARDIMONIUM HECTORITE', 'PHENOXYETHANOL', 'TOCOPHEROL', 'CI 77499', 'ALUMINUM HYDROXIDE', 'CI 77492', 'MICA']::text[]),
  ((select id from brands where name = 'PRICO'), 'カバーリキッド 200 ナチュラルオークル', 'foundation', false, 1480, 30, 'mL', '4901234000098', '#D9B28D', array['精製水', 'CYCLOPENTASILOXANE', 'ETHYLHEXYL METHOXYCINNAMATE', '酸化チタン', 'グリセリン', 'PEG-10 DIMETHICONE', 'BG', 'TALC', 'TRIETHOXYCAPRYLYLSILANE', 'SODIUM CHLORIDE', 'DISTEARDIMONIUM HECTORITE', 'フェノキシエタノール', 'ビタミンE', '酸化鉄（赤）', 'CI 77492', 'CITRIC ACID', 'ALUMINUM HYDROXIDE']::text[]),
  ((select id from brands where name = 'mode noir'), 'セラムファンデーション 300 オークル', 'foundation', false, 7800, 30, 'mL', '4901234000105', '#D2A177', array['WATER', 'DIMETHICONE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'ISODODECANE', 'LAURYL PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE', 'SILICA', 'ZINC OXIDE', 'SQUALANE', 'NIACINAMIDE', 'PANTHENOL', 'METHICONE', 'PHENOXYETHANOL', 'ALUMINUM HYDROXIDE', 'CI 77491', 'MICA', 'CITRIC ACID']::text[]),
  ((select id from brands where name = 'DAILY+'), 'デイリークッション 300 オークル', 'foundation', false, 1980, 30, 'mL', '4901234000112', '#D5A272', array['WATER', 'DIMETHICONE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'ISODODECANE', 'LAURYL PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE', 'SILICA', 'ZINC OXIDE', 'SQUALANE', 'NIACINAMIDE', 'PANTHENOL', 'METHICONE', 'PHENOXYETHANOL', 'MICA', 'CITRIC ACID', 'CI 77492', 'ALUMINUM HYDROXIDE', 'CI 77007']::text[]),
  ((select id from brands where name = 'SERAFI'), 'ライトカバークッション 100 ライトオークル', 'foundation', false, 4800, 30, 'mL', '4901234000119', '#E8C4A2', array['WATER', 'DIMETHICONE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'ISODODECANE', 'LAURYL PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE', 'SILICA', 'ZINC OXIDE', 'SQUALANE', 'NIACINAMIDE', 'PANTHENOL', 'METHICONE', 'PHENOXYETHANOL', 'MICA', 'CI 77492', 'CITRIC ACID', 'CI 77491']::text[]),
  ((select id from brands where name = 'KIRA COSME'), 'ツヤ肌ファンデ 400 ベージュオークル', 'foundation', false, 3600, 30, 'mL', '4901234000126', '#C79268', array['WATER', 'CYCLOPENTASILOXANE', 'ETHYLHEXYL METHOXYCINNAMATE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'PEG-10 DIMETHICONE', 'BUTYLENE GLYCOL', 'TALC', 'TRIETHOXYCAPRYLYLSILANE', 'SODIUM CHLORIDE', 'DISTEARDIMONIUM HECTORITE', 'PHENOXYETHANOL', 'TOCOPHEROL', 'ALUMINUM HYDROXIDE', 'MICA', 'CI 77499', 'CI 77491']::text[]),
  ((select id from brands where name = 'Nuance'), 'マットファンデ 500 ディープオークル', 'foundation', false, 2800, 30, 'mL', '4901234000133', '#B57F55', array['WATER', 'CYCLOPENTASILOXANE', 'ETHYLHEXYL METHOXYCINNAMATE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'PEG-10 DIMETHICONE', 'BUTYLENE GLYCOL', 'TALC', 'TRIETHOXYCAPRYLYLSILANE', 'SODIUM CHLORIDE', 'DISTEARDIMONIUM HECTORITE', 'PHENOXYETHANOL', 'TOCOPHEROL', 'CI 77499', 'MICA', 'CI 77491', 'CITRIC ACID']::text[]),
  ((select id from brands where name = 'PLUME'), 'グロウクッション 200 ナチュラルオークル', 'foundation', false, 5200, 30, 'mL', '4901234000140', '#DDAC8D', array['WATER', 'DIMETHICONE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'ISODODECANE', 'LAURYL PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE', 'SILICA', 'ZINC OXIDE', 'SQUALANE', 'NIACINAMIDE', 'PANTHENOL', 'METHICONE', 'PHENOXYETHANOL', 'CI 77499', 'CITRIC ACID', 'MICA', 'ALUMINUM HYDROXIDE']::text[]),
  ((select id from brands where name = 'PRICO'), 'ミネラルパウダーファンデ 100 ライトオークル', 'foundation', false, 1280, 30, 'mL', '4901234000147', '#E3CAA8', array['WATER', 'CYCLOPENTASILOXANE', 'ETHYLHEXYL METHOXYCINNAMATE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'PEG-10 DIMETHICONE', 'BUTYLENE GLYCOL', 'TALC', 'TRIETHOXYCAPRYLYLSILANE', 'SODIUM CHLORIDE', 'DISTEARDIMONIUM HECTORITE', 'PHENOXYETHANOL', 'TOCOPHEROL', 'MICA', 'CI 77499', 'CITRIC ACID', 'CI 77492']::text[]),
  ((select id from brands where name = 'DAILY+'), 'BBクリーム 400 ベージュオークル', 'foundation', false, 1180, 30, 'mL', '4901234000154', '#C68C6D', array['WATER', 'DIMETHICONE', 'TITANIUM DIOXIDE', 'GLYCERIN', 'ISODODECANE', 'LAURYL PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE', 'SILICA', 'ZINC OXIDE', 'SQUALANE', 'NIACINAMIDE', 'PANTHENOL', 'METHICONE', 'PHENOXYETHANOL', 'CI 77492', 'CITRIC ACID', 'MICA', 'CI 77491']::text[]),
  ((select id from brands where name = 'GRIT'), 'スカルプシャンプー クール', 'shampoo', true, 3300, 400, 'mL', '4901234000161', null, array['WATER', 'SODIUM LAURETH SULFATE', 'COCAMIDOPROPYL BETAINE', 'COCAMIDE MEA', 'GLYCERIN', 'PIROCTONE OLAMINE', 'ZINC PYRITHIONE', 'MENTHOL', 'SALICYLIC ACID', 'POLYQUATERNIUM-10', 'SODIUM CHLORIDE', 'CITRIC ACID', 'FRAGRANCE', 'PHENOXYETHANOL', 'DISODIUM EDTA']::text[]),
  ((select id from brands where name = 'CLEAR BASE'), '薬用スカルプ', 'shampoo', true, 980, 400, 'mL', '4901234000168', null, array['WATER', 'SODIUM LAURETH SULFATE', 'COCAMIDOPROPYL BETAINE', 'COCAMIDE MEA', 'GLYCERIN', 'PIROCTONE OLAMINE', 'MENTHOL', 'SALICYLIC ACID', 'SODIUM CHLORIDE', 'POLYQUATERNIUM-10', 'CITRIC ACID', 'FRAGRANCE', 'PHENOXYETHANOL', 'DISODIUM EDTA']::text[]),
  ((select id from brands where name = 'HARDSCALP'), 'デオスカルプシャンプー', 'shampoo', true, 4200, 400, 'mL', '4901234000175', null, array['WATER', 'SODIUM LAURETH SULFATE', 'COCAMIDOPROPYL BETAINE', 'COCAMIDE MEA', 'GLYCERIN', 'PIROCTONE OLAMINE', 'ZINC PYRITHIONE', 'MENTHOL', 'SALICYLIC ACID', 'POLYQUATERNIUM-10', 'SODIUM CHLORIDE', 'CITRIC ACID', 'PHENOXYETHANOL', 'FRAGRANCE', 'DISODIUM EDTA']::text[]),
  ((select id from brands where name = 'STOIC'), 'アミノ酸シャンプー', 'shampoo', true, 3800, 400, 'mL', '4901234000182', null, array['WATER', 'SODIUM COCOYL GLUTAMATE', 'LAURAMIDOPROPYL BETAINE', 'GLYCERIN', 'HYDROLYZED KERATIN', 'PANTHENOL', 'ZINC PYRITHIONE', 'ARGANIA SPINOSA KERNEL OIL', 'CAMELLIA SINENSIS LEAF EXTRACT', 'SODIUM HYALURONATE', 'BUTYLENE GLYCOL', 'CITRIC ACID', 'SODIUM BENZOATE', 'FRAGRANCE']::text[]),
  ((select id from brands where name = 'CLEAR BASE'), 'アミノ酸デイリー', 'shampoo', true, 1180, 400, 'mL', '4901234000189', null, array['WATER', 'SODIUM COCOYL GLUTAMATE', 'LAURAMIDOPROPYL BETAINE', 'GLYCERIN', 'PANTHENOL', 'HYDROLYZED KERATIN', 'ARGANIA SPINOSA KERNEL OIL', 'CAMELLIA SINENSIS LEAF EXTRACT', 'SODIUM HYALURONATE', 'BUTYLENE GLYCOL', 'CITRIC ACID', 'SODIUM BENZOATE', 'FRAGRANCE']::text[]),
  ((select id from brands where name = 'GRIT'), 'ボリュームアップシャンプー', 'shampoo', true, 2980, 400, 'mL', '4901234000196', null, array['WATER', 'SODIUM COCOYL GLUTAMATE', 'LAURAMIDOPROPYL BETAINE', 'GLYCERIN', 'PANTHENOL', 'HYDROLYZED KERATIN', 'ARGANIA SPINOSA KERNEL OIL', 'CAMELLIA SINENSIS LEAF EXTRACT', 'SODIUM HYALURONATE', 'BUTYLENE GLYCOL', 'CITRIC ACID', 'SODIUM BENZOATE', 'FRAGRANCE']::text[]),
  ((select id from brands where name = 'HARDSCALP'), 'フケ・かゆみ対策シャンプー', 'shampoo', true, 2480, 400, 'mL', '4901234000203', null, array['WATER', 'SODIUM LAURETH SULFATE', 'COCAMIDOPROPYL BETAINE', 'COCAMIDE MEA', 'GLYCERIN', 'PIROCTONE OLAMINE', 'ZINC PYRITHIONE', 'MENTHOL', 'SALICYLIC ACID', 'POLYQUATERNIUM-10', 'CITRIC ACID', 'SODIUM CHLORIDE', 'FRAGRANCE', 'PHENOXYETHANOL', 'DISODIUM EDTA']::text[]),
  ((select id from brands where name = 'STOIC'), 'ミントスカルプ', 'shampoo', true, 2200, 400, 'mL', '4901234000210', null, array['WATER', 'SODIUM LAURETH SULFATE', 'COCAMIDOPROPYL BETAINE', 'COCAMIDE MEA', 'GLYCERIN', 'PIROCTONE OLAMINE', 'ZINC PYRITHIONE', 'MENTHOL', 'SALICYLIC ACID', 'POLYQUATERNIUM-10', 'SODIUM CHLORIDE', 'FRAGRANCE', 'CITRIC ACID', 'PHENOXYETHANOL', 'DISODIUM EDTA']::text[]),
  ((select id from brands where name = 'GRIT'), 'スカルプトリートメント', 'treatment', true, 3300, 400, 'g', '4901234000217', null, array['WATER', 'CETEARYL ALCOHOL', 'BEHENTRIMONIUM CHLORIDE', 'DIMETHICONE', 'GLYCERIN', 'AMODIMETHICONE', 'STEARYL ALCOHOL', 'ISOPROPYL MYRISTATE', 'HYDROLYZED KERATIN', 'ARGANIA SPINOSA KERNEL OIL', 'PANTHENOL', 'FRAGRANCE', 'PHENOXYETHANOL', 'CITRIC ACID', 'BUTYLENE GLYCOL', 'SHEA BUTTER ETHYL ESTERS', 'TOCOPHEROL', 'SODIUM HYALURONATE']::text[]),
  ((select id from brands where name = 'CLEAR BASE'), 'デイリートリートメント', 'treatment', true, 880, 400, 'g', '4901234000224', null, array['WATER', 'CETEARYL ALCOHOL', 'BEHENTRIMONIUM CHLORIDE', 'DIMETHICONE', 'GLYCERIN', 'AMODIMETHICONE', 'STEARYL ALCOHOL', 'ISOPROPYL MYRISTATE', 'ARGANIA SPINOSA KERNEL OIL', 'HYDROLYZED KERATIN', 'PANTHENOL', 'FRAGRANCE', 'PHENOXYETHANOL', 'BUTYLENE GLYCOL', 'CITRIC ACID', 'SHEA BUTTER ETHYL ESTERS', 'TOCOPHEROL', 'SODIUM HYALURONATE']::text[]),
  ((select id from brands where name = 'STOIC'), 'リペアトリートメント', 'treatment', true, 3600, 400, 'g', '4901234000231', null, array['WATER', 'CETEARYL ALCOHOL', 'BEHENTRIMONIUM CHLORIDE', 'DIMETHICONE', 'AMODIMETHICONE', 'GLYCERIN', 'STEARYL ALCOHOL', 'ISOPROPYL MYRISTATE', 'HYDROLYZED KERATIN', 'ARGANIA SPINOSA KERNEL OIL', 'PANTHENOL', 'FRAGRANCE', 'PHENOXYETHANOL', 'CITRIC ACID', 'BUTYLENE GLYCOL', 'SHEA BUTTER ETHYL ESTERS', 'TOCOPHEROL', 'SODIUM HYALURONATE']::text[]),
  ((select id from brands where name = 'HARDSCALP'), 'クールトリートメント', 'treatment', true, 2600, 400, 'g', '4901234000238', null, array['WATER', 'BEHENTRIMONIUM CHLORIDE', 'CETEARYL ALCOHOL', 'DIMETHICONE', 'GLYCERIN', 'AMODIMETHICONE', 'STEARYL ALCOHOL', 'HYDROLYZED KERATIN', 'ISOPROPYL MYRISTATE', 'ARGANIA SPINOSA KERNEL OIL', 'PANTHENOL', 'FRAGRANCE', 'PHENOXYETHANOL', 'CITRIC ACID', 'BUTYLENE GLYCOL', 'SHEA BUTTER ETHYL ESTERS', 'TOCOPHEROL', 'SODIUM HYALURONATE']::text[]),
  ((select id from brands where name = 'LUMINA'), 'デイリーアイパレット 01 ブラウンベージュ', 'eyeshadow', false, 6800, 10.8, 'g', '4901234000245', '#E8D3C2', array['TALC', 'MICA', 'SYNTHETIC FLUORPHLOGOPITE', 'DIMETHICONE', 'SILICA', 'ZINC STEARATE', 'OCTYLDODECANOL', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'BORON NITRIDE', 'TOCOPHEROL', 'PHENOXYETHANOL', 'CI 15850', 'CI 77491', 'CI 77492', 'CI 77891']::text[]),
  ((select id from brands where name = 'PRICO'), '9色アイパレット 01 ブラウン', 'eyeshadow', false, 1480, 10.8, 'g', '4901234000252', '#EACFC2', array['TALC', 'MICA', 'SYNTHETIC FLUORPHLOGOPITE', 'DIMETHICONE', 'SILICA', 'OCTYLDODECANOL', 'ZINC STEARATE', 'CAPRYLIC/CAPRIC TRIGLYCERIDE', 'BORON NITRIDE', 'TOCOPHEROL', 'PHENOXYETHANOL', 'CI 77491', 'CI 15850', 'CI 42090', 'CI 77492']::text[]),
  ((select id from brands where name = 'mode noir'), 'クチュールアイパレット 02 モーヴ', 'eyeshadow', false, 8200, 7.2, 'g', '4901234000259', '#EFD2D2', array['MICA', 'TALC', 'CALCIUM ALUMINUM BOROSILICATE', 'SYNTHETIC FLUORPHLOGOPITE', 'MAGNESIUM MYRISTATE', 'DIMETHICONE', 'TIN OXIDE', 'SILICA', 'OCTYLDODECANOL', 'TOCOPHEROL', 'PHENOXYETHANOL', 'CI 77492', 'CI 42090', 'CI 77499', 'CI 15850']::text[]),
  ((select id from brands where name = 'DAILY+'), '6色アイパレット 02 ピンク', 'eyeshadow', false, 1280, 7.2, 'g', '4901234000266', '#ECCDD6', array['MICA', 'TALC', 'CALCIUM ALUMINUM BOROSILICATE', 'MAGNESIUM MYRISTATE', 'SYNTHETIC FLUORPHLOGOPITE', 'DIMETHICONE', 'TIN OXIDE', 'SILICA', 'OCTYLDODECANOL', 'TOCOPHEROL', 'PHENOXYETHANOL', 'CI 15850', 'CI 77891', 'CI 42090', 'CI 77492']::text[]);

insert into product_colors (product_id, pos, shade_name, hex) values
  (1, 0, '03 テラコッタ', '#B8604A'),
  (2, 0, '03 テラコッタ', '#BB6249'),
  (3, 0, '05 レッドブリック', '#9E3B33'),
  (4, 0, '05 レッドブリック', '#993B2D'),
  (5, 0, '01 ベアヌード', '#C98A78'),
  (6, 0, '04 モーヴピンク', '#B96C81'),
  (7, 0, '06 コーラルオレンジ', '#D96A4B'),
  (8, 0, '07 ダークプラム', '#7A3348'),
  (9, 0, '08 ミルクティー', '#C79A82'),
  (10, 0, '02 ローズブラウン', '#A85F5A'),
  (11, 0, '04 モーヴピンク', '#BC687E'),
  (12, 0, '06 コーラルオレンジ', '#D6684E'),
  (13, 0, '200 ナチュラルオークル', '#DDB18C'),
  (14, 0, '200 ナチュラルオークル', '#D9B28D'),
  (15, 0, '300 オークル', '#D2A177'),
  (16, 0, '300 オークル', '#D5A272'),
  (17, 0, '100 ライトオークル', '#E8C4A2'),
  (18, 0, '400 ベージュオークル', '#C79268'),
  (19, 0, '500 ディープオークル', '#B57F55'),
  (20, 0, '200 ナチュラルオークル', '#DDAC8D'),
  (21, 0, '100 ライトオークル', '#E3CAA8'),
  (22, 0, '400 ベージュオークル', '#C68C6D'),
  (35, 0, 'ベース', '#E8D3C2'),
  (35, 1, 'ミルクベージュ', '#D9B999'),
  (35, 2, 'ライトブラウン', '#B98A62'),
  (35, 3, 'テラコッタ', '#B8604A'),
  (35, 4, 'ローズブラウン', '#A85F5A'),
  (35, 5, 'ブリック', '#9E3B33'),
  (35, 6, 'ダークブラウン', '#6E4630'),
  (35, 7, 'シマーゴールド', '#D9A441'),
  (35, 8, 'プラム', '#7A3348'),
  (36, 0, 'ベース', '#EACFC2'),
  (36, 1, 'ミルクベージュ', '#D8B49E'),
  (36, 2, 'ライトブラウン', '#B98E62'),
  (36, 3, 'テラコッタ', '#BB5C4C'),
  (36, 4, 'ローズブラウン', '#A85C5E'),
  (36, 5, 'ブリック', '#A23D38'),
  (36, 6, 'ダークブラウン', '#72432B'),
  (36, 7, 'シマーゴールド', '#D7A946'),
  (36, 8, 'プラム', '#792F47'),
  (37, 0, 'シアーピンク', '#EFD2D2'),
  (37, 1, 'ベビーピンク', '#E3A9AE'),
  (37, 2, 'モーヴ', '#B96C81'),
  (37, 3, 'コーラル', '#D96A4B'),
  (37, 4, 'ワインレッド', '#8E2F3E'),
  (37, 5, 'シルバー', '#C9C5C1'),
  (38, 0, 'シアーピンク', '#ECCDD6'),
  (38, 1, 'ベビーピンク', '#E0ADB2'),
  (38, 2, 'モーヴ', '#B3717B'),
  (38, 3, 'コーラル', '#DA6847'),
  (38, 4, 'ワインレッド', '#903439'),
  (38, 5, 'シルバー', '#CEBFBC');

insert into reviews (product_id, author_name, author_key, rating, body, image_phash, posted_at) values
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'mikan_88', 'mikan_88', 4, 'カバー力は十分。ただ夕方は小鼻がよれるので部分的にパウダーがいる。', null, now() - interval '40 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'kt_no_diary', 'kt_no_diary', 3, '色は合うけど乾燥する。冬は下地を保湿系にしないと厳しかった。', null, now() - interval '34 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'sekkachi', 'sekkachi', 5, '崩れにくさは今まで使った中で一番。値段は高いが減りは遅い。', null, now() - interval '28 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'yuu_cosme', 'yuu_cosme', 2, '自分の肌には黄みが強すぎた。首との差が出る。', null, now() - interval '22 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'nagi_r', 'nagi_r', 4, '少量で伸びる。マスクにはそこそこ着く。', null, now() - interval '16 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'pr_account_a', 'pr_account_a', 5, '本当に神コスメすぎる！朝塗ったら夜まで崩れない！みんな買って！ #pr', 'phash_aaa111', now() - interval '20 hours'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'pr_account_b', 'pr_account_b', 5, 'まじで神コスメすぎる！朝塗ったら夜まで崩れないです！みんな買うべき！', 'phash_aaa111', now() - interval '19 hours'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'pr_account_c', 'pr_account_c', 5, '神コスメすぎました！朝塗って夜まで崩れない！絶対買って！', 'phash_bbb222', now() - interval '18 hours'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'brand_fan_1', 'brand_fan_1', 5, 'このブランドは全部良い。今回も最高でした。提供いただきました。', null, now() - interval '17 hours'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'brand_fan_1', 'brand_fan_1', 5, 'やっぱりこのブランドは裏切らない。リピート確定です。', null, now() - interval '16 hours'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'セラムファンデーション%' limit 1), 'brand_fan_1', 'brand_fan_1', 5, '何度もリピートしています。文句なしの品質。', null, now() - interval '15 hours'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'mode noir' and p.name like 'マットリップ%' limit 1), 'brand_fan_1', 'brand_fan_1', 5, 'このブランドは全部良い。文句なし。', null, now() - interval '3 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'PRICO' and p.name like 'カバーリキッド%' limit 1), 'mikan_88', 'mikan_88', 4, '値段の割にちゃんと隠れる。崩れ方は値段なり。', null, now() - interval '10 days'),
  ((select p.id from products p join brands b on b.id = p.brand_id where b.name = 'PRICO' and p.name like 'カバーリキッド%' limit 1), 'nagi_r', 'nagi_r', 4, '高いやつと並べても正直違いが分からなかった。', null, now() - interval '5 days');

-- 別名辞書を投入（成分マスタの truncate で消えるため、シードのたびに入れ直す）
select seed_ingredient_aliases();

-- IDF を数え直して成分ベクトルを再生成
select refresh_ingredient_idf();

-- 不正判定を初期化
select recompute_review_trust(id) from products;
